name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: make install

      - name: Test
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          SERVER_HOSTNAME: ${{ secrets.SERVER_HOSTNAME }}
          DWH_DB: ${{ secrets.DWH_DB }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
        run: make test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t alejandroparedeslatorre/flask-app:latest .

      - name: Push Docker image
        run: docker push alejandroparedeslatorre/flask-app:latest